version: "3.8"

services:
  mongo-example:
    image: mongo:latest
    container_name: mongo_example
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_USERNAME: daffamrizqi
      MONGO_INITDB_PASSWORD: Naufal11
      MONGO_INITDB_DATABASE: admin