version: "3.8"

services:
  # short syntax
  mongo-volume_compose:
    image: mongo:latest
    container_name: mongo_volume_compose
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_USERNAME: daffamrizqi
      MONGO_INITDB_PASSWORD: Naufal11
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "mongo-data1:/data/db"

    # long syntax
  mongo-volume_compose_2:
    image: mongo:latest
    container_name: mongo_volume_compose_2
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_USERNAME: daffamrizqi
      MONGO_INITDB_PASSWORD: Naufal11
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: volume
        source: mongo-data2
        target: "/data/db"
        read_only: false

volumes:
  mongo-data1:
    name: mongo-data1
  mongo-data2:
    name: mongo-data2